# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_lostads_ads_created_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostads',
            old_name='ads_created_dt',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='lostads',
            old_name='ads_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='lostads',
            old_name='ads_title',
            new_name='title',
        ),
    ]
