# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0004_auto_20170121_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostads',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
